### PR TITLE
Corrects the DM for global-to-local scatter

### LINKED ISSUE #141: Initialization of initial condition is broken
The global-to-local scatter is incorrectly using `rdy->aux_dm` instead of `rdy->dm` for the following scatter.

```
      // scatter global-to-local
      PetscCall(DMGlobalToLocalBegin(rdy->aux_dm, global, INSERT_VALUES, local));
      PetscCall(DMGlobalToLocalEnd(rdy->aux_dm, global, INSERT_VALUES, local));
```

### PR DESCRIPTION
**Pull request by bishtgautam**
The IC vector that is loaded has nDOF=3 (for SWE). Thus, `rdy->dm` should be used
instead of `rdy->aux_dm` for the global-to-local scatter.

Fixes #141

### CODE REVIEW

File: src/rdysetup.c [hunk 1]
```diff
@@ -797,14 +798,21 @@ static PetscErrorCode InitSolution(RDy rdy) {
       PetscCall(VecLoad(natural, viewer));
       PetscCall(PetscViewerDestroy(&viewer));
 
+      // check the block size of the initial condition vector agrees with the block size of rdy->X
+      PetscInt nblocks_nat;
+      PetscCall(VecGetBlockSize(natural, &nblocks_nat));
+      PetscCheck((ndof == nblocks_nat), rdy->comm, PETSC_ERR_USER,
+                 "The block size of the initial condition ('%d') do not match with the nDOFs ('%d')", nblocks_nat, ndof);
```
Comment (jeff-cohere) [inline src/rdysetup.c:805]: consider "with the nDOFs" -> "the number of DOFs"

Comment (jeff-cohere) [reply src/rdysetup.c:805]: Also, "do" -> "does"

**Review by jeff-cohere — APPROVED** [review]
Looks good. I left a very minor suggestion for the wording of an error message.
