### PR TITLE
Fixes HDF5 checkpoint file

### LINKED ISSUE #298: HDF5 checkpoint file is creating data for incorrect size
The size of the `/fields/solution` has the dimension of `ntimesteps x ngridcells x nDOFs`.
Similarly, `/time` has the dimension of `ntimesteps`. Both of thse datasets should not
have a dimension of `ntimesteps`.

### PR DESCRIPTION
**Pull request by bishtgautam**
- The data in the `.h5` restart files is of the correct size
- Fortran interfaces are written to write/read HDF5 checkpoint file

Closes #298

### CODE REVIEW

File: src/f90-mod/rdycore.F90 [hunk 1]
```diff
@@ -934,6 +949,40 @@ subroutine RDyWriteOneDOFGlobalVecToBinaryFile(rdy_, filename, global_vec, ierr)
...
+  subroutine RDyWriteHDF5CheckpointFile(rdy_, filename_base, ierr)
+    use petscvec
+    type(RDy),  intent(inout) :: rdy_
+    character(len=1024), intent(in) :: filename_base
+    integer,    intent(out)   :: ierr
+
+    integer                      :: n
+    character(len=1024), pointer :: checkpoint_filename_base
+
+    n = len_trim(filename_base)
```
Comment (jeff-cohere) [inline src/f90-mod/rdycore.F90]: Why don't we truncate this at 1023 to prevent the buffer overflow that Copilot is worried about?
```
n = min(1023, len_trim(filename_base))
```

**Comment by bishtgautam** [comment]
@knepley , @jeff-cohere , The h5 restart file has the following data:

```
h5dump -H checkpoints/ex2b.rdycore.r.0100.h5
HDF5 "checkpoints/ex2b.rdycore.r.0100.h5" {
GROUP "/" {
   ATTRIBUTE "dmplex_storage_version" {
      DATATYPE  H5T_STRING {
         STRSIZE 6;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_ASCII;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
   }
   ATTRIBUTE "petsc_version_git" {
      DATATYPE  H5T_STRING {
         STRSIZE 8;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_ASCII;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
   }
   GROUP "fields" {
      DATASET "solution" {
         DATATYPE  H5T_IEEE_F64LE
         DATASPACE  SIMPLE { ( 44, 3 ) / ( 44, 3 ) }
      }
   }
   GROUP "metadata" {
      ATTRIBUTE "dt" {
         DATATYPE  H5T_IEEE_F64LE
         DATASPACE  SCALAR
      }
      ATTRIBUTE "nproc" {
         DATATYPE  H5T_STD_I32LE
         DATASPACE  SCALAR
      }
      ATTRIBUTE "step" {
         DATATYPE  H5T_STD_I32LE
         DATASPACE  SCALAR
      }
      ATTRIBUTE "t" {
         DATATYPE  H5T_IEEE_F64LE
         DATASPACE  SCALAR
      }
   }
}
}
```

But, I'm getting the following error when attempting to read the .h5 file;

```
INFO: Reading checkpoint file checkpoints/ex2b.rdycore.r.0100.h5...
[0]PETSC ERROR: --------------------- Error Message --------------------------------------------------------------
[0]PETSC ERROR: Unexpected data in file
[0]PETSC ERROR: Dataset //fields/solution stored with timesteps? FALSE Timestepping pushed? TRUE
[0]PETSC ERROR: See https://petsc.org/release/faq/ for trouble shooting.
[0]PETSC ERROR: PETSc Release Version 3.24.1, unknown
[0]PETSC ERROR: /home/gbisht/projects/rdycore/e3sm/externals/rdycore/build-openmpi11-netcdf481-b522cb8c110-2025-10-29/driver/tests/../rdycore with 1 MPI process(es) and PETSC_ARCH openmpi11-netcdf481-b522cb8c110-2025-10-29 on aqua by gbisht Wed Dec 24 11:04:42 2025
[0]PETSC ERROR: Configure options: --download-cmake --download-fblaslapack --download-parmetis --with-hdf5-dir=/home/gbisht/packages/installations/gcc11 --with-zlib-dir=/home/gbisht/packages/installations/gcc11 --download-metis --download-scalapack --download-sowing --with-netcdf-dir=/home/gbisht/packages/installations/gcc11/ --download-pnetcdf --download-triangle --download-exodusii --download-libceed --download-cgns --download-muparser --with-mpi-dir=/home/gbisht/packages/installations/gcc11 --download-sowing-cc=/home/gbisht/packages/installations/gcc11/bin/mpicc --download-sowing-cxx=/home/gbisht/packages/installations/gcc11/bin/mpicxx PETSC_ARCH=openmpi11-netcdf481-b522cb8c110-2025-10-29
[0]PETSC ERROR: #1 PetscViewerHDF5CheckTimestepping_Internal() at /home/gbisht/projects/petsc/petsc_master/src/vec/is/utils/hdf5/hdf5io.c:29
[0]PETSC ERROR: #2 PetscViewerHDF5ReadInitialize_Private() at /home/gbisht/projects/petsc/petsc_master/src/vec/is/utils/hdf5/hdf5io.c:40
[0]PETSC ERROR: #3 PetscViewerHDF5Load_Internal() at /home/gbisht/projects/petsc/petsc_master/src/vec/is/utils/hdf5/hdf5io.c:247
[0]PETSC ERROR: #4 PetscViewerHDF5Load() at /home/gbisht/projects/petsc/petsc_master/src/vec/is/utils/hdf5/hdf5io.c:327
[0]PETSC ERROR: #5 VecLoad_HDF5() at /home/gbisht/projects/petsc/petsc_master/src/vec/vec/utils/vecio.c:137
[0]PETSC ERROR: #6 VecLoad_Default() at /home/gbisht/projects/petsc/petsc_master/src/vec/vec/utils/vecio.c:219
[0]PETSC ERROR: #7 VecLoad_Plex_Local() at /home/gbisht/projects/petsc/petsc_master/src/dm/impls/plex/plex.c:830
[0]PETSC ERROR: #8 VecLoad() at /home/gbisht/projects/petsc/petsc_master/src/vec/vec/interface/vector.c:1179
[0]PETSC ERROR: #9 ReadCheckpointFile() at /home/gbisht/projects/rdycore/e3sm/externals/rdycore/src/checkpoint.c:300
[0]PETSC ERROR: #10 RDySetup() at /home/gbisht/projects/rdycore/e3sm/externals/rdycore/src/rdysetup.c:1392
[0]PETSC ERROR: #11 main() at /home/gbisht/projects/rdycore/e3sm/externals/rdycore/driver/main.c:1690
[0]PETSC ERROR: PETSc Option Table entries:
[0]PETSC ERROR: -dist_dm_distribute_save_sf true (source: code)
[0]PETSC ERROR: -dm_plex_filename planar_dam_10x5.msh (source: code)
[0]PETSC ERROR: -restart checkpoints/ex2b.rdycore.r.0100.h5 (source: command line)
[0]PETSC ERROR: ----------------End of Error Message -------send entire error message to petsc-maint@mcs.anl.gov----------
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_SELF
with errorcode 79.
```

**Comment by bishtgautam** [comment]
@knepley, the solution `Vec` is saved to a `.h5` file differently when running with 1 vs 2 MPI tasks: `fields/solution` vs `/solution`.

- Using 1 MPI task

```
h5dump -H checkpoints/ex2b.rdycore.r.0100.h5
HDF5 "checkpoints/ex2b.rdycore.r.0100.h5" {
GROUP "/" {
   ATTRIBUTE "dmplex_storage_version" {
      DATATYPE  H5T_STRING {
         STRSIZE 6;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_ASCII;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
   }
   ATTRIBUTE "petsc_version_git" {
      DATATYPE  H5T_STRING {
         STRSIZE 8;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_ASCII;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
   }
   GROUP "fields" {
      DATASET "solution" {
         DATATYPE  H5T_IEEE_F64LE
         DATASPACE  SIMPLE { ( 44, 3 ) / ( 44, 3 ) }
      }
   }
   GROUP "metadata" {
      ATTRIBUTE "dt" {
         DATATYPE  H5T_IEEE_F64LE
         DATASPACE  SCALAR
      }
      ATTRIBUTE "nproc" {
         DATATYPE  H5T_STD_I32LE
         DATASPACE  SCALAR
      }
      ATTRIBUTE "step" {
         DATATYPE  H5T_STD_I32LE
         DATASPACE  SCALAR
      }
      ATTRIBUTE "t" {
         DATATYPE  H5T_IEEE_F64LE
         DATASPACE  SCALAR
      }
   }
}
}
```
- Using 2 MPI tasks
```
h5dump -H checkpoints/ex2b.rdycore.r.0100.h5
HDF5 "checkpoints/ex2b.rdycore.r.0100.h5" {
GROUP "/" {
   GROUP "metadata" {
      ATTRIBUTE "dt" {
         DATATYPE  H5T_IEEE_F64LE
         DATASPACE  SCALAR
      }
      ATTRIBUTE "nproc" {
         DATATYPE  H5T_STD_I32LE
         DATASPACE  SCALAR
      }
      ATTRIBUTE "step" {
         DATATYPE  H5T_STD_I32LE
         DATASPACE  SCALAR
      }
      ATTRIBUTE "t" {
         DATATYPE  H5T_IEEE_F64LE
         DATASPACE  SCALAR
      }
   }
   DATASET "solution" {
      DATATYPE  H5T_IEEE_F64LE
      DATASPACE  SIMPLE { ( 44, 3 ) / ( 44, 3 ) }
   }
}
}
```
How to save the `Vec` so that it is identical when run on 1 or 2 MPI tasks? Or, how to tell the reading of the `Vec` to check `fields/solution` and `/solution`?

**Comment by bishtgautam** [comment]
Adding `PetscViewerHDF5PushGroup`/`PetscViewerHDF5PopGroup` to the viewer fixes the failing tests ([9c2236f](https://github.com/RDycore/RDycore/pull/362/commits/9c2236f7b34a28dde3230f31b39e0763f3982a29))

**Comment by knepley** [comment]
@bishtgautam Just checking that this is fixed, and nothing is left to do.
